---

- name: create partition
  parted:
    device: "{{ device_name }}"
    number: 1
    flags: [lvm]
    state: present
    part_end: "{{ device_size }}"

# - name: create partition
#   parted: 
#      device: /dev/sdc
#      number: 1
#      flags: [lvm]
#      state: present
#      part_end: 1.5GB